#!/bin/bash

# read-validate: validate input

invalid_input () {
	echo "invalid input '$REPLY'" >&2
	exit 1
}

read -p "Enter a single item > "

# input is empty (invalid)
[[ -z "$REPLY" ]] && invalid_input

# input is multiple items (invalid) 
(( "$(echo "$REPLY" | wc -w)" > 1 )) && invalid_input

# is input a valid filename?
if [[ "$REPLY" =~ ^[-[:alnum:]\._]+$ ]]; then
	echo "'$REPLY' is a valid filename."
	if [[ -e "$REPLY" ]]; then
		echo "And file '$REPLY' exists."
	else
		echo "However, file '$REPLY' does not exist."
	fi

	# is input a floating point number?
	if [[ "$REPLY
	" =~ ^-?[[:digit:]]*\.[[:digit:]]+$ ]]; then
	else
		echo 
		
